name: 'Maven release'
description: 'Release maven branch'
author: 'ivosahlik@seznam.cz'

runs:
  using: composite
  steps:
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
