name: 'Maven release'
description: 'Release maven branch'
author: 'petr.steckovic@vodafone.com'

runs:
  using: 'composite'
  steps:
    - name: Checkout the repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn clean package
