name: 36 - Slack composite
description: test
inputs:
  secret:
    description: Secret
    required: true

outputs:
  response:
    description: Whether dependencies were installed or not
    value: ${{ steps.call-slack.outputs.response }}

runs:
  using: composite
  steps:
    - name: Call slack api
      id: call-slack
      run: |        
        RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" -X POST \
          -H "Content-type: application/json" \
          -H "Content-Length: 2" \
          -H "Host: https://hooks.slack.com" \
          -H "Accept: */*" \
          https://hooks.slack.com/services/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 \
          -d '{"text":"Hello, Team Building!"}')
                
        echo $RESPONSE
        
        echo "response=$RESPONSE" >> $GITHUB_OUTPUT
      shell: bash

# https://api.slack.com/
# Activate Incoming Webhooks
# https://app.slack.com/

#Sample curl request to post to a channel:
# curl -X POST -H 'Content-type: application/json' --data '{"text":"Hello, World!"}' https://hooks.slack.com/services/<SLACK_TOKEN>
