name: 02 - Workflow Events label

# https://docs:github:com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows:
on:
#  push:
#    tags:
#      - r*
#    branches: [ "main" ]
#  pull_request:
# https://crontab.cronhub.io/
#  schedule:
#    - cron: '0 0 * * *'
  pull_request:
    types: [ labeled ]
jobs:
  add-comment:
    if: github.event.label.name == 'help wanted'
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Run a one-line script
        run: echo Hello, world!
      - name: Run on label bug
        if: github.event.label.name == 'bug'
        run: echo Hello, bug!
