name: 02 - Workflow Events

# https://docs:github:com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows:
on:
  push:
    branches: [ "main" ]
  pull_request:
# https://crontab.cronhub.io/
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Show the trigger
        run: echo "I've been triggered by a(n) ${{ github.event_name }} event."
