name: 05 - 1 - Event Filters and Activity Types

on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - main
      - 'dev-*' # dev-new dev-this-is-new
      - 'feature/**' # feature/new feature/new/button
      - 'releases/**-alpha' # ! character to indicate which branches should be excluded -> branches-ignore

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running whenever a PR is opened or synchronized AND base branch is main"
