name: 20 - Workflow Security

on:
#  pull_request:
  workflow_dispatch:

jobs:
  test-no-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Get branch name
        run: echo "Branch name is ${{ github.head_ref || github.ref_name }} "
      - name: Check PR title
        run: |
          title=${{ github.head_ref || github.ref_name }} 
          echo $title
          if [[ $title =~ ^feat ]]; then
            echo "PR is a feature!"
            exit 0
          else
            echo "PR is not a feature"
            exit 1
          fi
#  unsafe-pr:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v4
#      - name: Get branch name
#        run: echo "Branch name is ${{ github.head_ref }}"
#      - name: Check PR title
#        run: |
#          title=${{ github.event.pull_request.title }}
#          echo $title
#          if [[ $title =~ ^feat ]]; then
#            echo "PR is a feature!"
#            exit 0
#          else
#            echo "PR is not a feature"
#            exit 1
#          fi
#  safer-pr:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v4
#      - name: Check PR title
#        env:
#          TITLE: ${{ github.event.pull_request.title }}
#        run: |
#          if [[ $TITLE =~ ^feat ]]; then
#            echo "PR is a feature!"
#            exit 0
#          else
#            echo "PR is not a feature"
#            exit 1
#          fi
#  js-safer-pr:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v4
#      - name: Check PR title
#        uses: ./.github/actions/security-safe-input
#        with:
#          pr-title: ${{ github.event.pull_request.title }}
