name: 29-Auto approve PR

on:
  workflow_dispatch:

jobs: 
  auto-approve-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Auto approve PR
        run: |
          curl -X POST -H "Authorization: Bearer ${{ secrets.TERRAFORM_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/ivosahlik/github-actions-sample/pulls/${{ github.event.pull_request.number }}/reviews \
            -d '{"event":"APPROVE", "body": "Approved by GHA workflow: Auto approve test installations"}'
          echo "PR approved"

  auto-approve-pr-test-1-response:
    runs-on: ubuntu-latest
    steps:
      - name: Auto approve PR TEST 1
        run: |
          RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" -X POST -H "Authorization: Bearer ${{ secrets.TERRAFORM_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/ivosahlik/github-actions-sample/pulls/${{ github.event.pull_request.number }}/reviews \
            -d '{"event":"APPROVE", "body": "Approved by GHA workflow: Auto approve test installations"}')
          
          echo $RESPONSE
          
          if [ "$RESPONSE" -eq 200 ]; then
            echo "PR approved"
            echo "Pull request [${{ github.event.pull_request.number }}](https://github.com/VFCZ-Digital/dxl-configurations/pull/${{ github.event.pull_request.number }}) is automatically approved, as there are only pre-approved files." >> $GITHUB_STEP_SUMMARY
          elif [ "$RESPONSE" -eq 401 ]; then
            echo "Bad credentials"
            exit 1
          else
            echo "Failed to approve PR. HTTP status code: $RESPONSE"
            exit 1
          fi
  auto-approve-pr-test-2-response:
    runs-on: ubuntu-latest
    steps:
      - name: Auto approve PR TEST 2
        run: |
          RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" -X GET -H "Authorization: Bearer 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" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/ivosahlik/github-actions-sample/pulls)
          
          echo $RESPONSE
          
          if [ "$RESPONSE" -eq 200 ]; then
            echo "List pull request"
          elif [ "$RESPONSE" -eq 401 ]; then
            echo "Bad credentials"
            exit 1
          else
            echo "Failed to approve PR. HTTP status code: $RESPONSE"
            exit 1
          fi

  settings-xml:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Auto approve PR
        shell: bash
        run: |
          mkdir -p ~/.m2/repository
          echo "${{ vars.MAVEN_SETTINGS_TEST }}" > ~/.m2/settings.xml
          cd ~/.m2
          pwd
          ls -la
          cat ~/.m2/settings.xml
          ls -la
          echo "${{ vars.MAVEN_SETTINGS_TEST}}"

