name: 29-Auto approve PR

on:
  workflow_dispatch:

jobs: 
  auto-approve-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Auto approve PR
        run: |
          curl -X POST -H "Authorization: Bearer ${{ secrets.GH_TOKEN_PR_AUTOMERGE}}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/ivosahlik/github-actions-sample/pulls/${{ github.event.pull_request.number }}/reviews \
            -d '{"event":"APPROVE", "body": "Approved by GHA workflow: Auto approve test installations"}'
          echo "PR approved"
  settings-xml:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Auto approve PR
        run: |
          mkdir -p ~/.m2/repository
          echo "${{ env.MAVEN_SETTINGS_TEST }}" > ~/.m2/settings.xml
          cd ~/.m2
          pwd
          ls -la
          cat ~/.m2/settings.xml
          ls -la
          echo "${{ env.MAVEN_SETTINGS_TEST}}"

