name: 29-Auto approve PR

on:
  workflow_dispatch:

jobs: 
  auto-approve-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Auto approve PR
        run: |
          curl -X POST -H "Authorization: Bearer ${{ secrets.GH_TOKEN_PR_AUTOMERGE }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/ivosahlik/github-actions-sample/pulls/${{ github.event.pull_request.number }}/reviews \
            -d '{"event":"APPROVE", "body": "Approved by GHA workflow: Auto approve test installations"}'
          echo "PR approved"

  pass-response:
    runs-on: ubuntu-latest
    steps:
      - name: Call APi and get response
        id: get-response
        run: |
          RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" -X POST -H "Authorization: Bearer ${{ secrets.GH_TOKEN_PR_AUTOMERGE }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/ivosahlik/github-actions-sample/pulls/${{ github.event.pull_request.number }}/reviews \
            -d '{"event":"APPROVE", "body": "Approved by GHA workflow: Auto approve test installations"}')
          echo "response=$RESPONSE" >> $GITHUB_ENV
      - name: Check response
        run: |
          echo ${{ env.response }}
          
          if [ ${{ env.response }} -eq 200 ]; then
            echo "PR approved"
          elif [ ${{ env.response }} -eq 401 ]; then
            echo "Bad credentials"
            exit 1
          else
            echo "Failed to approve PR. HTTP status code: ${{ env.response }}"
            exit 1
          fi

      - name: I will be skipped
        if: ${{ success() }}
        run: echo "I will print if previous steps succeed."
      - name: I will execute
        if: ${{ failure() }}
        run: echo "I will print if any previous step fails."
      - name: I will execute
        if: ${{ !cancelled() }}
        run: echo "I will always print, except when the workflow is cancelled."
      - name: I will execute when cancelled
        if: ${{ cancelled() }}
        run: echo "I will print if the workflow has been cancelled."

  auto-approve-pr-test-1-response:
    runs-on: ubuntu-latest
    steps:
      - name: Auto approve PR TEST 1
        run: |
          RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" -X POST -H "Authorization: Bearer ${{ secrets.GH_TOKEN_PR_AUTOMERGE }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/ivosahlik/github-actions-sample/pulls/${{ github.event.pull_request.number }}/reviews \
            -d '{"event":"APPROVE", "body": "Approved by GHA workflow: Auto approve test installations"}')
          
          echo $RESPONSE
          
          if [ "$RESPONSE" -eq 200 ]; then
            echo "PR approved"
          elif [ "$RESPONSE" -eq 401 ]; then
            echo "Bad credentials"
            exit 1
          else
            echo "Failed to approve PR. HTTP status code: $RESPONSE"
            exit 1
          fi
      - name: I will be skipped
        if: ${{ success() }}
        run: echo "I will print if previous steps succeed."
      - name: I will execute
        if: ${{ failure() }}
        run: echo "I will print if any previous step fails."
      - name: I will execute
        if: ${{ !cancelled() }}
        run: echo "I will always print, except when the workflow is cancelled."
      - name: I will execute when cancelled
        if: ${{ cancelled() }}
        run: echo "I will print if the workflow has been cancelled."
  list-pull-requests-test-2-response:
    runs-on: ubuntu-latest
    steps:
      - name: List pull requests - TEST 2
        run: |
          RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" -X GET -H "Authorization: Bearer ${{ secrets.GH_TOKEN_PR_AUTOMERGE }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/ivosahlik/github-actions-sample/pulls)
          
          echo $RESPONSE
          
          if [ "$RESPONSE" -eq 200 ]; then
            echo "List pull request"
          elif [ "$RESPONSE" -eq 401 ]; then
            echo "Bad credentials"
            exit 1
          else
            echo "Failed to approve PR. HTTP status code: $RESPONSE"
            exit 1
          fi
      - name: I will be skipped
        if: ${{ success() }}
        run: echo "I will print if previous steps succeed."
      - name: I will execute
        if: ${{ failure() }}
        run: echo "I will print if any previous step fails."
      - name: I will execute
        if: ${{ !cancelled() }}
        run: echo "I will always print, except when the workflow is cancelled."
      - name: I will execute when cancelled
        if: ${{ cancelled() }}
        run: echo "I will print if the workflow has been cancelled."
  call-automerge-composite-actions-test-3-call-composite-response:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Call Composite Action
        id: call-composite
        uses: ./.github/actions/automerge-composite
        with:
         secret: ${{ secrets.GH_TOKEN_PR_AUTOMERGE }}

      - name: Use Composite Action Output
        run: |
          echo "The response code is ${{ steps.call-composite.outputs.response }}"
          if [ ${{ steps.call-composite.outputs.response }} -eq 200 ]; then
            echo "PR approved"
          elif [ ${{ steps.call-composite.outputs.response }} -eq 401 ]; then
            echo "Bad credentials"
            exit 1
          else
            echo "Failed to approve PR. HTTP status code: ${{ steps.call-composite.outputs.response }}"
            exit 1
          fi

      - name: I will be skipped
        if: ${{ success() }}
        run: echo "I will print if previous steps succeed."
      - name: I will execute
        if: ${{ failure() }}
        run: echo "I will print if any previous step fails."
      - name: I will execute
        if: ${{ !cancelled() }}
        run: echo "I will always print, except when the workflow is cancelled."
      - name: I will execute when cancelled
        if: ${{ cancelled() }}
        run: echo "I will print if the workflow has been cancelled."
  call-list-pull-requests-composite-actions-test-4-call-api:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Call Composite Action
        id: list-pull-requests
        uses: ./.github/actions/list-pull-requests
        with:
          secret: ${{ secrets.GH_TOKEN_PR_AUTOMERGE }}

      - name: Use Composite Action Output
        run: |
          echo "The response code is ${{ steps.list-pull-requests.outputs.response }}"
          if [ ${{ steps.list-pull-requests.outputs.response }} -eq 200 ]; then
            echo "PR approved"
          elif [ ${{ steps.list-pull-requests.outputs.response }} -eq 401 ]; then
            echo "Bad credentials"
            exit 1
          else
            echo "Failed to approve PR. HTTP status code: ${{ steps.list-pull-requests.outputs.response }}"
            exit 1
          fi

      - name: I will be skipped
        if: ${{ success() }}
        run: echo "I will print if previous steps succeed."
      - name: I will execute
        if: ${{ failure() }}
        run: echo "I will print if any previous step fails."
      - name: I will execute
        if: ${{ !cancelled() }}
        run: echo "I will always print, except when the workflow is cancelled."
      - name: I will execute when cancelled
        if: ${{ cancelled() }}
        run: echo "I will print if the workflow has been cancelled."
  settings-xml:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Auto approve PR
        shell: bash
        run: |
          mkdir -p ~/.m2/repository
          echo "${{ vars.MAVEN_SETTINGS_TEST }}" > ~/.m2/settings.xml
          cd ~/.m2
          pwd
          ls -la
          cat ~/.m2/settings.xml
          ls -la
          echo "${{ vars.MAVEN_SETTINGS_TEST}}"

