name: 28-shell commands

on:
  workflow_dispatch:

jobs: 
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: Auto approve PR
        run: |
          curl -X POST -H "Authorization: Bearer ${{ secrets.SECRETS_TOKEN}}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/ivosahlik/pulls/${{ github.event.pull_request.number }}/reviews \
            -d '{"event":"APPROVE", "body": "Approved by GHA workflow: Auto approve test installations"}'
          echo "PR approved"