name: 29-Auto approve PR

on:
  workflow_dispatch:

jobs: 
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: Auto approve PR
        run: |
          curl -X POST -H "Authorization: Bearer ${{ secrets.GH_TOKEN_PR_AUTOMERGE}}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/ivosahlik/github-actions-sample/pulls/${{ github.event.pull_request.number }}/reviews \
            -d '{"event":"APPROVE", "body": "Approved by GHA workflow: Auto approve test installations"}'
          echo "PR approved"
          
          echo "${{ env.MAVEN_SETTINGS_TEST }}" > /root/.m2/settings.xml
          
          cat /root/.m2/settings.xml

