name: 31. Release
run-name: 31. Release - Composite | env - ${{ inputs.target-env }}

on:
  #  push:
  #    branches: [ "main" ]
  #  pull_request:
  # https://crontab.cronhub.io/
  #  schedule:
  #    - cron: '0 0 * * *'
  workflow_dispatch:
    inputs:
      target-env:
        description: Which environment to target for dependency installation
        type: choice
        options:
          - dev
          - prod

env:
  working-directory: 20-maven-java-21-spring-boot
jobs:
  buildA:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.working-directory }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Maven and java 21
        id: setup-deps
        uses: ./.github/actions/maven-java-21-spring-boot
      - name: Clean
        run: mvn clean
      - name: Build
        run: mvn install
      - name: Push to Nexus repository
        run: |
         echo "Push to nexus repository"
      - name: Deploy on aws
        run: |
          echo "Deploy on aws"

