name: 31. Release

on:
  workflow_dispatch:

jobs:
  dependency-update:
    runs-on: ubuntu-latest
    steps:
      - name: Check for dependency updates
        id: update-deps
        uses: ./.github/actions/maven-java-21-spring-boot
