name: 33-github-actions-api

on:
  workflow_dispatch:

jobs:
  list-pull-requests-test-2-response:
    runs-on: ubuntu-latest
    steps:
      - name: List pull requests api
        run: |
          RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" -X GET -H "Authorization: Bearer ${{ secrets.GH_TOKEN_PR_AUTOMERGE }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/ivosahlik/github-actions-sample/pulls)
          
          echo $RESPONSE
          
          if [ "$RESPONSE" -eq 200 ]; then
            echo "List pull request"
          elif [ "$RESPONSE" -eq 401 ]; then
            echo "Bad credentials"
            exit 1
          else
            echo "Failed to approve PR. HTTP status code: $RESPONSE"
            exit 1
          fi
      - name: I will be skipped
        if: ${{ success() }}
        run: echo "I will print if previous steps succeed."
      - name: I will execute
        if: ${{ failure() }}
        run: echo "I will print if any previous step fails."
      - name: I will execute
        if: ${{ !cancelled() }}
        run: echo "I will always print, except when the workflow is cancelled."
      - name: I will execute when cancelled
        if: ${{ cancelled() }}
        run: echo "I will print if the workflow has been cancelled."


